"""The `paper/` scaffold and its bibliography stay internally consistent.

Motivated by plans/07 SS 7.8, whose definition of done for the letter asks for
two mechanical things this module supplies:

  * "Every citation BibTeX-verified against INSPIRE" -- the acceptance the
    run-19 ledger wrote as "a new checker prints `0 unresolved` over
    paper/refs.bib" (T27).  Three things are counted as unresolved, and the
    standalone line prints their sum.  Two of them make refs.bib and the
    letter's `\cite` commands an exact correspondence: a `\cite` key in
    main.tex with no entry in refs.bib, and an entry in refs.bib that no
    `\cite` reaches.  The second of those is why refs.bib holds the letter's
    35 works alone: the 40 further records that cover the source reference
    lists live in refs_reserve.bib, which only draft mode compiles, and
    promoting one is a move between the two files.  The third walks the
    numbered reference lists of Report 1 and of the coherent note -- the two
    documents plans/07 WP6 says the letter's text is drafted from -- and
    asserts that every numbered entry of both is represented by at least one
    record in the two files together.  That mapping is carried in the files
    themselves, as a `% cited by R1[n]/N[m]` comment above every entry;
  * "Four letter figures + Table 1 regenerated by one `paper/` build script"
    (T25).  Two legs.  The register in `paper/figs/README.md` must point at
    producing scripts that are really there; and, now that the drivers exist,
    the build products must be present and Table 1 must still be the table
    those drivers would write.  The second leg is what makes "every number in
    Table 1 was produced by a driver" mechanical rather than a promise:
    `paper/table1.tex` is compared cell by cell with `paper/figs/table1.json`,
    and every raw value behind those cells is compared with the measurement it
    claims to come from in `figs/fig2.json` or `figs/fig4.json`.  Hand-editing
    the table, or rebuilding the figures without rebuilding the table, fails
    the sweep.

Scope, and what this module deliberately does NOT do.

  * It never touches the network.  `refs.bib` was fetched from INSPIRE once, by
    a one-off fetcher under the run-19 scratchpad, and `paper/refs_provenance.md`
    is that fetch's audit trail.  Re-querying INSPIRE on every consistency sweep
    would make the sweep slow, flaky and dependent on a third party's uptime, so
    what is checked here is the *shape* of the result: an entry either looks
    like a machine-fetched INSPIRE record or says in a `note` field that it was
    written by hand.
  * It does not check volumes and page numbers.  plans/07 SS 7.3 row 10 puts
    that re-verification at submission, not at scaffolding time, and six of the
    entries are 2025-2026 preprints whose journal data have not settled.
  * It does not check the letter's physics.  What it checks about the numbers
    the letter puts in front of a reader without a sentence around them --
    Table 1, its caption and the abstract -- is that each of them is a number
    the programme has already published: every one is declared in the
    `SOURCED` table below against the string Report 1's template or the
    manual's expected-numbers table (docs/reproduction_manual.md SS 7) prints
    it in, that string must still be in that document verbatim, and the
    letter's own value must agree with a number inside it to the precision
    that number is printed at.  A number that is in neither document is
    declared against the driver that measured it, with the reason; there are
    five of those and they are listed in the table.  Adding a number to the
    abstract or to Table 1 without declaring it fails the sweep, as does
    editing one of the two documents so that the string it was read out of is
    gone.  What it checks about the rest of the text (T26/T28) is weaker --
    that every number in it is *attributed*: `paper/main.tex`
    carries a "% src:" comment on every body line that quotes a number, and on
    the line above every displayed equation, naming the report section, plan
    section or build artifact the number comes from.  A number with no source
    comment fails the sweep; whether the source says what the sentence says is
    a reading, not a grep, and belongs to the author.
  * It refuses, in `main.tex` and `paper/cover_letter.md`, any form retired in
    `tools/retired_numbers.json`.  `tools/checks/retired_strings.py` owns that
    list but its corpus is the reports, the plans, the docs and the module
    docstrings of `evgen/` and `fastsim/`; `paper/` is outside it, and a letter
    that quoted a withdrawn number would pass every other check in the tree.

Standalone use (this is the T27 acceptance line):

    python3 tools/checks/paper_numbers.py
"""

import pathlib
import re

try:                                  # loaded by tools/consistency_check.py
    ROOT = checker.ROOT               # noqa: F821  (injected by the loader)
    _STANDALONE = False
except NameError:                     # run directly
    ROOT = pathlib.Path(__file__).resolve().parents[2]
    _STANDALONE = True

PAPER = ROOT / "paper"

# The letter's reference budget (plans/07 SS 7.2: "~40 references"; the WP6
# brief for the text caps it at 35).  If the authors add the companion
# Report 1 as a 36th citation at submission -- the letter's own source, which
# it does not yet cite (R-PAPER 2026-09-16, item 24) -- this becomes 36 and
# that entry moves from refs_reserve.bib into refs.bib.
MAX_CITED = 35

# The abstract budget of the same brief.
MAX_ABSTRACT_WORDS = 120

# The marker the letter's own header must carry while it is unreviewed, and
# the word the body must not contain, so that a document describing itself as
# a draft cannot reach the body text of a paper.
DRAFT_MARKER = "DRAFT v0, 2026-09-16, for the authors' review"

# The files T22 was asked to scaffold.  `figs/` is a directory with a register
# in it rather than an image, which is why its README is named explicitly.
REQUIRED = [
    "main.tex",
    "refs.bib",
    "refs_reserve.bib",
    "build.sh",
    "README.md",
    "refs_provenance.md",
    "figs/README.md",
]

# --- reading the sources ----------------------------------------------------

# A BibTeX entry head: "@article{Key," at the start of a line.  Comment lines in
# refs.bib carry no "@" precisely so that BibTeX itself does not mistake one for
# an entry, and this pattern inherits that guarantee.
ENTRY = re.compile(r'^@(\w+)\s*\{\s*([^,\s]+)\s*,', re.M)

# \cite{a,b}, \citep[see][]{a}, \citet{a}, \nocite{a}.  "*" is not a key.
CITE = re.compile(r'\\(?:no)?cite[a-zA-Z]*\s*(?:\[[^\]]*\]\s*){0,2}\{([^}]*)\}')

FIELD = re.compile(r'^\s*(\w+)\s*=\s*[{"]', re.M)


def _strip_tex_comments(text):
    """Drop everything after an unescaped % on each line."""
    out = []
    for line in text.split("\n"):
        i, keep = 0, line
        while i < len(line):
            if line[i] == "%" and (i == 0 or line[i - 1] != "\\"):
                keep = line[:i]
                break
            i += 1
        out.append(keep)
    return "\n".join(out)


# The letter's own bibliography, and the reserve beside it.  refs.bib is kept
# in exact correspondence with main.tex's \cite commands; refs_reserve.bib
# holds the records that cover the two source reference lists and that the
# letter does not cite, and only draft mode compiles it.
BIB = "refs.bib"
RESERVE = "refs_reserve.bib"


def _bib_entries(name=BIB):
    """[(kind, key, body)] for one bibliography file, in file order."""
    path = PAPER / name
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    heads = list(ENTRY.finditer(text))
    entries = []
    for i, m in enumerate(heads):
        end = heads[i + 1].start() if i + 1 < len(heads) else len(text)
        entries.append((m.group(1).lower(), m.group(2), text[m.start():end]))
    return entries


# main.tex guards its draft bibliography with \ifdraftbib ... \else ... \fi:
# draft mode adds refs_reserve.bib and emits \nocite{*} so that a build checks
# that every record of both files parses, and the letter itself is built with
# \draftbibfalse and compiles refs.bib alone.  A \nocite{*} sitting in the
# branch that is switched off is not a citation of everything, and reading it
# as one would switch off the two directions checked below, so the conditional
# is resolved the way TeX would resolve it before the keys are collected.
# (the lookbehind keeps \newif\ifdraftbib, which declares the switch and
# opens no conditional, from being read as the start of one)
_DRAFT_SPAN = re.compile(r"(?<!\\newif)\\ifdraftbib(.*?)\\fi", re.S)
_DRAFT_SET = re.compile(r"\\draftbib(true|false)\b")


def _draft_bib(body):
    """Is \draftbibtrue the setting in force?  (comments already removed)"""
    settings = _DRAFT_SET.findall(body)
    return bool(settings) and settings[-1] == "true"


def _resolve_draft(body):
    draft = _draft_bib(body)

    def take(m):
        branches = m.group(1).split(r"\else", 1)
        if draft:
            return branches[0]
        return branches[1] if len(branches) > 1 else " "
    return _DRAFT_SPAN.sub(take, body)


def _cite_keys():
    """Every key cited by paper/main.tex, comments removed and the draft
    bibliography switch resolved.  A live \nocite{*} -> (keys, True)."""
    path = PAPER / "main.tex"
    if not path.exists():
        return set(), False
    body = _resolve_draft(_strip_tex_comments(path.read_text(encoding="utf-8")))
    keys, star = set(), False
    for m in CITE.finditer(body):
        for k in m.group(1).split(","):
            k = k.strip()
            if k == "*":
                star = True
            elif k:
                keys.add(k)
    return keys, star


def _fig_register():
    """[(label, script)] read out of the table in paper/figs/README.md."""
    path = PAPER / "figs/README.md"
    if not path.exists():
        return []
    rows = []
    for line in path.read_text(encoding="utf-8").split("\n"):
        if not line.startswith("| Fig."):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3:
            continue
        m = re.search(r'`([^`]+\.py)`', cells[2])
        if m:
            pub = re.search(r'`([^`]+\.png)`', cells[3]) if len(cells) > 3 else None
            rows.append((cells[0], m.group(1),
                         pub.group(1) if pub else None))
    return rows


# --- coverage of the two source reference lists -----------------------------

# Every entry of refs.bib carries a "% cited by ..." comment naming the entries
# of the two source lists it came from: R1[n] for
# reports/cos2phi_money_plots_report.template.html and N[n] for
# docs/note_cos2phi_coherent_6Li.md.  That comment is what makes "0 unresolved"
# a statement about the letter's sources rather than about its own \cite
# commands, which the skeleton has none of yet.
CITED_BY = re.compile(r'^%\s*cited by\s+(.+)$', re.M)
LABEL = re.compile(r'(R1|N)\[(\d+)\]')

REPORT1 = "reports/cos2phi_money_plots_report.template.html"
NOTE = "docs/note_cos2phi_coherent_6Li.md"


def _source_list_sizes():
    """(n_report1, n_note): how many numbered entries each source list has."""
    n1 = n2 = 0
    p1 = ROOT / REPORT1
    if p1.exists():
        text = p1.read_text(encoding="utf-8")
        m = re.search(r'<div\s+class="refs[^"]*">(.*?)</div>', text, re.S)
        if m:
            n1 = len(set(int(x) for x in
                         re.findall(r'<p>\s*\[(\d+)\]', m.group(1))))
    p2 = ROOT / NOTE
    if p2.exists():
        text = p2.read_text(encoding="utf-8")
        m = re.search(r'^## References\s*$(.*?)^## ', text, re.S | re.M)
        body = m.group(1) if m else ""
        n2 = len(set(int(x) for x in re.findall(r'^\[(\d+)\]', body, re.M)))
    return n1, n2


def _covered_labels():
    """The (list, number) pairs both bibliography files account for."""
    labels, n = set(), 0
    for name in (BIB, RESERVE):
        path = PAPER / name
        if not path.exists():
            continue
        for m in CITED_BY.finditer(path.read_text(encoding="utf-8")):
            n += 1
            for kind, num in LABEL.findall(m.group(1)):
                labels.add((kind, int(num)))
    return labels, n


def _coverage_issues():
    """Every numbered entry of both source lists is represented in the two
    bibliography files together."""
    entries = _bib_entries() + _bib_entries(RESERVE)
    labels, n_comments = _covered_labels()
    bad = []
    if n_comments != len(entries):
        bad.append("%d of %d entries of refs.bib and %s carry a "
                   "'%% cited by' comment" % (n_comments, len(entries), RESERVE))
    n1, n2 = _source_list_sizes()
    if n1 == 0:
        bad.append("could not read the reference list of %s" % REPORT1)
    if n2 == 0:
        bad.append("could not read the reference list of %s" % NOTE)
    for kind, n, where in (("R1", n1, REPORT1), ("N", n2, NOTE)):
        missing = [i for i in range(1, n + 1) if (kind, i) not in labels]
        if missing:
            bad.append("%s: entries %s are cited by no record of refs.bib or "
                       "%s" % (where, ", ".join("[%d]" % i for i in missing),
                               RESERVE))
    return bad


# --- the checks -------------------------------------------------------------

def _scaffold_issues():
    if not PAPER.is_dir():
        return ["paper/ does not exist"]
    return ["paper/%s is missing" % f for f in REQUIRED
            if not (PAPER / f).exists()]


def _bib_issues():
    """The two directions between main.tex and refs.bib, plus duplicate keys.

    Returns (issues, n_cited, n_unresolved), where "unresolved" counts both
    directions: a \cite with no entry, and an entry with no \cite.  The
    second direction is what keeps refs.bib shippable -- it is the file that
    goes to the journal, and a record in it that nothing cites is either a
    citation dropped from the text or a reserve record that strayed out of
    refs_reserve.bib.  The reserve is exempt by living in that other file,
    which main.tex compiles only under \draftbibtrue.
    """
    entries = _bib_entries()
    if not entries:
        return (["paper/refs.bib holds no BibTeX entry"], 0, 0)
    bad = []
    seen = {}
    for _, key, _ in entries:
        if key in seen:
            bad.append("duplicate key %s in refs.bib" % key)
        seen[key] = True
    reserve = {}
    for _, key, _ in _bib_entries(RESERVE):
        if key in reserve:
            bad.append("duplicate key %s in %s" % (key, RESERVE))
        if key in seen:
            bad.append("%s is in refs.bib and in %s: BibTeX would take "
                       "whichever it read first" % (key, RESERVE))
        reserve[key] = True
    cited, star = _cite_keys()
    unresolved = sorted(k for k in cited if k not in seen)
    for k in unresolved:
        if k in reserve:
            bad.append(r"\cite{%s} in main.tex resolves only in %s: move that "
                       "entry into refs.bib, which is the file the letter "
                       "compiles" % (k, RESERVE))
        else:
            bad.append(r"\cite{%s} in main.tex resolves to no refs.bib entry"
                       % k)
    uncited = sorted(k for k in seen if k not in cited)
    if not star:
        for k in uncited:
            bad.append("refs.bib entry %s is reached by no \cite in main.tex: "
                       "either cite it or move it to %s" % (k, RESERVE))
    unresolved = unresolved + ([] if star else uncited)
    # The budget survives beside the correspondence: plans/07 SS 7.2 gives the
    # letter ~40 references and the WP6 brief caps it at MAX_CITED, and a
    # letter that silently grew past that would be a different document.
    if not star and cited and len(cited) > MAX_CITED:
        bad.append("main.tex cites %d distinct works; plans/07 SS 7.2 budgets "
                   "at most %d for a letter" % (len(cited), MAX_CITED))
    if not star and not cited:
        bad.append("main.tex cites nothing and does not run with "
                   r"\draftbibtrue: the bibliography would be empty")
    return (bad, len(cited), len(unresolved))


def _provenance_issues():
    """Every entry of either file is INSPIRE-shaped or flagged hand-written."""
    bad = []
    for kind, key, body in _bib_entries() + _bib_entries(RESERVE):
        fields = set(f.lower() for f in FIELD.findall(body))
        hand = "HAND-WRITTEN" in body
        if hand:
            if kind != "misc":
                bad.append("%s is flagged HAND-WRITTEN but is @%s, not @misc"
                           % (key, kind))
            if "note" not in fields:
                bad.append("%s is flagged HAND-WRITTEN outside a note field" % key)
            continue
        # a machine-fetched INSPIRE record always carries at least one of these
        if not fields & {"eprint", "doi", "journal", "reportnumber"}:
            bad.append("%s has no eprint, doi, journal or reportNumber, and is "
                       "not flagged HAND-WRITTEN -- was it typed by hand?" % key)
        if "title" not in fields or "author" not in fields:
            bad.append("%s is missing a title or an author field" % key)
    prov = PAPER / "refs_provenance.md"
    if prov.exists():
        text = prov.read_text(encoding="utf-8")
        for _, key, body in _bib_entries() + _bib_entries(RESERVE):
            if "HAND-WRITTEN" in body and key not in text:
                bad.append("hand-written entry %s is not accounted for in "
                           "refs_provenance.md" % key)
    return bad


def _figure_issues():
    rows = _fig_register()
    if len(rows) != 4:
        return ["paper/figs/README.md registers %d letter figures, expected 4"
                % len(rows)]
    bad = []
    for label, script, _pub in rows:
        if not (ROOT / script).exists():
            bad.append("%s names producing script %s, which does not exist"
                       % (label, script))
    return bad


def _frontmatter_issues():
    path = PAPER / "main.tex"
    if not path.exists():
        return ["paper/main.tex is missing"]
    text = path.read_text(encoding="utf-8")
    bad = []
    # the programme's author line, affiliation and writing-assistance line --
    # required of everything paper-like in this repository
    for needle, what in (
            (r"\author[anl]{C.~Peng}", "the C. Peng author line"),
            (r"\author[anl]{J.~Zhou}", "the J. Zhou author line"),
            ("Physics Division, Argonne National Laboratory", "the ANL affiliation"),
            ("Writing assisted by Claude (Anthropic)", "the writing-assistance line"),
    ):
        if needle not in text:
            bad.append("main.tex does not carry %s" % what)
    # plans/07 WP6 asks for "elsarticle, two-column" and does not choose
    # between the journal layout and the preprint one.  main.tex carries both
    # class lines, one active and one commented, so that the letter can be read
    # in either; the check is that the active one is an elsarticle two-column
    # line and that the alternative is still recorded.
    active = [ln.strip() for ln in text.split("\n")
              if ln.strip().startswith(r"\documentclass")]
    if len(active) != 1:
        bad.append("main.tex has %d uncommented \\documentclass line(s), "
                   "expected exactly 1" % len(active))
    elif "elsarticle" not in active[0] or "twocolumn" not in active[0]:
        bad.append("main.tex's class line %r is not an elsarticle two-column "
                   "line, which plans/07 WP6 asks for" % active[0])
    for spelling in ("[final,5p,times,twocolumn]{elsarticle}",
                     "[preprint,twocolumn,12pt]{elsarticle}"):
        if spelling not in text:
            bad.append("main.tex no longer records the %s layout; both belong "
                       "in the file, one active and one commented" % spelling)
    return bad


# --- the built letter figures and Table 1 (T25) -----------------------------

# Stem -> the caption macro main.tex writes in that figure's \caption{}.  The
# drivers emit the \newcommand; main.tex \input{}s it.  Spelled out rather
# than derived because main.tex names them in words.
CAPTION_MACRO = {
    "fig1": "figonecaption",
    "fig2": "figtwocaption",
    "fig3": "figthreecaption",
    "fig4": "figfourcaption",
}

# Every file `paper/build.sh` is required to (re)generate.  These are committed
# artifacts, not build litter -- paper/.gitignore covers the LaTeX droppings
# only -- so the sweep can insist on them the same way it insists on the
# published PNGs of evgen/.
def _build_products():
    out = []
    for stem in sorted(CAPTION_MACRO):
        for suffix in (".pdf", ".png", ".json", "_caption.tex"):
            out.append("figs/%s%s" % (stem, suffix))
    out += ["table1.tex", "figs/table1.json"]
    return out


def _missing_products():
    return [f for f in _build_products() if not (PAPER / f).exists()]


def _load_json(rel):
    import json
    return json.loads((PAPER / rel).read_text(encoding="utf-8"))


# A generated tabular row: "cell & cell & ... \\" .  \midrule, \toprule and
# the \multicolumn section headings are not rows of numbers and are skipped.
def _tex_rows(text):
    rows = []
    for line in text.split("\n"):
        s = line.strip()
        if not s.endswith(r"\\") or s.startswith("%"):
            continue
        s = s[:-2].strip()
        if s.startswith(r"\multicolumn") or "&" not in s:
            continue
        cells = [c.strip() for c in s.split("&")]
        if any(c.startswith(r"\toprule") for c in cells):
            continue
        rows.append(cells)
    return rows


# The header row names the columns; it is the one tabular row whose first cell
# is not a bin.  Dropped by matching the JSON's row count from the end.
def _table_issues():
    missing = _missing_products()
    if missing:
        return ["paper/%s is missing: run `bash paper/build.sh --figures`" % m
                for m in missing]
    bad = []
    tj = _load_json("figs/table1.json")
    rows = tj.get("rows", [])
    tex = (PAPER / "table1.tex").read_text(encoding="utf-8")

    if r"%% paper/table1.tex -- GENERATED" not in tex:
        bad.append("paper/table1.tex has lost its GENERATED banner: it is "
                   "meant to be written whole by paper/table1.py")

    # --- leg 1: the typeset cells are the driver's cells --------------------
    tex_rows = _tex_rows(tex)
    if len(tex_rows) < len(rows):
        bad.append("paper/table1.tex has %d tabular data row(s), "
                   "figs/table1.json carries %d"
                   % (len(tex_rows), len(rows)))
    else:
        body = tex_rows[-len(rows):] if rows else []
        for cells, r in zip(body, rows):
            want = [r["bin"], r["n"], r["amp"], r["err1"], r["err10"],
                    r["significance"]]
            if cells != want:
                bad.append(
                    "paper/table1.tex row %r does not match the cells "
                    "paper/table1.py wrote into figs/table1.json (%r): the "
                    "table has been edited by hand, or the figures were "
                    "rebuilt without rebuilding it"
                    % (" & ".join(cells), " & ".join(want)))

    # --- leg 2: those cells' raw values are the drivers' measurements -------
    f2 = _load_json("figs/fig2.json")
    f4 = _load_json("figs/fig4.json")
    spots = {s["spot"]: s for s in f2.get("spots", [])}
    for r in rows:
        v = r.get("values", {})
        if r["kind"] == "inclusive":
            s = spots.get(r["spot"])
            if s is None:
                bad.append("Table 1 carries inclusive super-bin %r, which "
                           "figs/fig2.json does not measure" % (r["spot"],))
                continue
            want = {"n_1yr": s["n_1yr"], "amp": s["a_truth"],
                    "err_1yr": s["err_1yr"], "err_10yr": s["err_10yr"],
                    "significance_1yr": s["significance_1yr"]}
            where = "figs/fig2.json spot %s" % r["spot"]
        else:
            b = f4["best_bin"]
            want = {"n_1yr": b["n_1yr"], "amp": f4["a2_per_pzz"],
                    "err_1yr": f4["err_1yr"], "err_10yr": f4["err_10yr"],
                    "significance_1yr": abs(f4["a2_per_pzz"]
                                            / f4["err_1yr"])}
            where = "figs/fig4.json"
        for k, wanted in want.items():
            got = v.get(k)
            if got is None or abs(float(got) - float(wanted)) > \
                    1e-9 * max(1.0, abs(float(wanted))):
                bad.append("Table 1 %s = %r for the %s row, but %s measures "
                           "%r: Table 1 is stale against the figures"
                           % (k, got, r["kind"], where, wanted))

    # --- leg 3: the table's own footing is the figures' ---------------------
    for key, src_obj, src_name in (("pzz", f2["settings"], "figs/fig2.json"),
                                   ("lumi_1yr", f2["settings"], "figs/fig2.json"),
                                   ("lumi_10yr", f2["settings"], "figs/fig2.json")):
        if key in tj and key in src_obj and \
                abs(float(tj[key]) - float(src_obj[key])) > 1e-12:
            bad.append("figs/table1.json %s = %r against %s's %r"
                       % (key, tj[key], src_name, src_obj[key]))
    return bad


def _provenance_of_built_figures():
    """Each figN.json names the producing script and published figure that
    figs/README.md registers for that figure."""
    missing = _missing_products()
    if missing:
        return []          # already reported by _table_issues
    rows = _fig_register()
    if len(rows) != 4:
        return []          # already reported by _figure_issues
    bad = []
    for n, (label, script, pub) in enumerate(rows, start=1):
        stem = "fig%d" % n
        d = _load_json("figs/%s.json" % stem)
        if d.get("figure") != stem:
            bad.append("figs/%s.json calls itself %r" % (stem, d.get("figure")))
        got = d.get("source_script")
        if got != script:
            bad.append("%s is registered against %s but figs/%s.json was "
                       "built from %r" % (label, script, stem, got))
        if pub and d.get("published_figure") != pub:
            bad.append("%s is registered as condensing %s but figs/%s.json "
                       "names %r" % (label, pub, stem, d.get("published_figure")))
        cap = (PAPER / ("figs/%s_caption.tex" % stem)).read_text(
            encoding="utf-8")
        macro = CAPTION_MACRO[stem]
        if ("\\newcommand{\\%s}" % macro) not in cap:
            bad.append("figs/%s_caption.tex does not define \\%s, which "
                       "main.tex writes into that figure's caption"
                       % (stem, macro))
    main = PAPER / "main.tex"
    if main.exists():
        text = main.read_text(encoding="utf-8")
        for stem, macro in sorted(CAPTION_MACRO.items()):
            if ("\\input{figs/%s_caption}" % stem) not in text:
                bad.append("main.tex does not \\input{figs/%s_caption}, so "
                           "the generated caption is not the one typeset"
                           % stem)
            if ("\\%s" % macro) not in text:
                bad.append("main.tex never uses \\%s" % macro)
        if r"\input{table1}" not in text:
            bad.append(r"main.tex does not \input{table1}, so the generated "
                       "table is not the one typeset")
    return bad


# --- the letter's text (T26 / T28) -----------------------------------------

# Structural lines whose digits are not quoted quantities: the class line, the
# package list, the title and address, the float machinery, the bibliography.
_STRUCTURAL = re.compile(
    r"^\s*\\(documentclass|usepackage|PassOptionsToPackage|graphicspath|input|"
    r"includegraphics|newif|draftbib|journal|title|author|address|keyword|"
    r"bibliographystyle|bibliography|label|emergencystretch|Urlmuskip|"
    r"begin|end|caption|centering|section|maketitle)\b")

# Digits that carry no measurement and are removed before the test: citation
# and reference keys, isotope and power superscripts, subscripts, and control
# sequences (\Delta, \times, \sigma).
_NON_NUMERIC = [
    re.compile(r"\\(?:cite|ref|label|input|includegraphics|newcommand)\s*"
               r"(?:\[[^\]]*\])?\{[^}]*\}"),
    re.compile(r"[\^_]\s*\{[^{}]*\}"),        # ^{6}, _{zz}, ^{-1}, ^{33}
    re.compile(r"[\^_]\s*\\?\w"),             # ^2, _m
    re.compile(r"\\[a-zA-Z]+"),               # \Delta, \times, \sigma
]

# What survives that stripping is then tested for a QUANTITY rather than for a
# digit.  A quoted quantity is a decimal, a number of two digits or more, or a
# percentage; a bare single digit is notation -- "spin-1", "IP6", "PYTHIA 8",
# "cos 2phi", "A > 2", "Section 3", "(1,-2,1)" -- and carries nothing to
# source.  Numbers written as powers of ten survive as their mantissa (the
# exponent is a stripped superscript), so 5.2e9 and 1e-3 are both caught.
_QUANTITY = re.compile(r"\d+\.\d|\d{2,}|\d+\s*\\%")

# What a "% src:" comment has to name.  Every token is a place in this
# repository a number can be read out of.
_SRC = re.compile(
    r"(?:R[0-4]\s+(?:sec\s+[0-9][0-9A-Za-z.]*|Table\s+\d+|Appendix\s+A)"
    r"|note\s+sec\s+\d+"
    r"|manual\s+sec\s+[0-9.]+"
    r"|plans/\d\d\s+sec\s+[0-9.]+"
    r"|figs/(?:fig[1-4]|table1)\.json"
    r"|Table\s+1)")

_FLOAT = re.compile(r"^\s*\\begin\{(figure\*?|table\*?)\}")
_MATH_BEGIN = re.compile(r"^\s*\\begin\{(equation\*?|multline\*?|align\*?|gather\*?)\}")


def _split_comment(line):
    """(code, comment) for one TeX line; comment is '' when there is none."""
    i = 0
    while i < len(line):
        if line[i] == "%" and (i == 0 or line[i - 1] != "\\"):
            return line[:i], line[i + 1:]
        i += 1
    return line, ""


def _quotes_a_number(code):
    s = code
    # a per-cent sign is \% and would lose its digit to the control-sequence
    # rule, so the percentage test runs on the unstripped line
    if re.search(r"\d+\s*\\%", s):
        return True
    for pat in _NON_NUMERIC:
        s = pat.sub(" ", s)
    return bool(_QUANTITY.search(s))


def _text_issues():
    """Every number in the body names where it came from."""
    path = PAPER / "main.tex"
    if not path.exists():
        return ["paper/main.tex is missing"]
    lines = path.read_text(encoding="utf-8").split("\n")

    # the header must say what the document is, and the body must not
    head = "\n".join(lines[:40])
    bad = []
    if DRAFT_MARKER not in head:
        bad.append("paper/main.tex's header comment does not carry %r"
                   % DRAFT_MARKER)

    try:
        start = next(i for i, l in enumerate(lines)
                     if l.strip().startswith(r"\begin{document}"))
    except StopIteration:
        return bad + [r"paper/main.tex has no \begin{document}"]

    depth_float = 0
    depth_math = 0
    in_front = False             # \title, \author, \address, \keyword
    in_abstract = False
    pending_src = False          # a "% src:" comment seen on a recent line
    for n, line in enumerate(lines[start:], start=start + 1):
        code, comment = _split_comment(line)
        # the front matter's digits are a ZIP code and an isotope label, not
        # quoted quantities; its abstract is body text and is checked.
        if r"\begin{frontmatter}" in code:
            in_front = True
        if r"\end{frontmatter}" in code:
            in_front = False
        if r"\begin{abstract}" in code:
            in_abstract = True
        if r"\end{abstract}" in code:
            in_abstract = False
        if in_front and not in_abstract:
            continue
        has_src = "src:" in comment and _SRC.search(comment) is not None
        if not code.strip():
            if has_src:
                pending_src = True
            continue

        if _FLOAT.search(code):
            depth_float += 1
        if depth_float and re.search(r"\\end\{(figure\*?|table\*?)\}", code):
            depth_float -= 1
            continue
        if depth_float:
            continue            # captions and graphics are generated elsewhere

        if _MATH_BEGIN.search(code):
            if not (has_src or pending_src):
                bad.append("main.tex:%d opens a displayed equation with no "
                           "'%% src:' comment above it" % n)
            depth_math += 1
            pending_src = False
            continue
        if depth_math:
            if re.search(r"\\end\{(equation\*?|multline\*?|align\*?|gather\*?)\}",
                         code):
                depth_math -= 1
            continue

        # the word "draft" belongs in the header, never in the text
        if re.search(r"(?i)\bdrafts?\b", code):
            bad.append("main.tex:%d calls the document a draft in the body; "
                       "that belongs in the header comment only" % n)

        if _STRUCTURAL.search(code):
            pending_src = has_src
            continue
        if _quotes_a_number(code) and not has_src:
            bad.append("main.tex:%d quotes a number with no '%% src:' comment "
                       "naming where it comes from: %r" % (n, code.strip()))
        pending_src = has_src
    return bad


def _abstract_issues():
    path = PAPER / "main.tex"
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    m = re.search(r"\\begin\{abstract\}(.*?)\\end\{abstract\}", text, re.S)
    if not m:
        return [r"paper/main.tex has no abstract environment"]
    body = _strip_tex_comments(m.group(1))
    body = re.sub(r"\$[^$]*\$", "M", body)          # one math span = one word
    body = re.sub(r"\\[a-zA-Z]+\*?", " ", body)
    body = body.replace("{", " ").replace("}", " ").replace("~", " ")
    n = len(body.split())
    if n > MAX_ABSTRACT_WORDS:
        return ["paper/main.tex's abstract is %d words; the letter budgets "
                "at most %d" % (n, MAX_ABSTRACT_WORDS)]
    return []


def _cover_letter_issues():
    """plans/07 SS 7.8: the cover letter states the two verified firsts."""
    path = PAPER / "cover_letter.md"
    if not path.exists():
        return ["paper/cover_letter.md is missing (plans/07 SS 7.8)"]
    text = path.read_text(encoding="utf-8")
    bad = []
    for needle, what in (
            ("C. Peng and J. Zhou", "the programme's author line"),
            ("Physics Division, Argonne National Laboratory",
             "the ANL affiliation"),
            ("Writing assisted by Claude (Anthropic)",
             "the writing-assistance line"),
            (DRAFT_MARKER, "the draft marker in its header comment"),
    ):
        if needle not in text:
            bad.append("paper/cover_letter.md does not carry %s" % what)
    # the two firsts, each by the fact that makes it checkable
    if "1803.11206" not in text:
        bad.append("paper/cover_letter.md does not name the JLab letter of "
                   "intent (arXiv:1803.11206), which is what makes the first "
                   "of the two firsts a verified one")
    if "139053" not in text:
        bad.append("paper/cover_letter.md does not name Phys. Lett. B 858 "
                   "(2024) 139053, the calculation whose forward citations "
                   "were swept for the second of the two firsts")
    return bad


def _retired_in_paper_issues():
    """No form retired in tools/retired_numbers.json reaches the letter.

    tools/checks/retired_strings.py owns the list; its corpus is the reports,
    the plans, the docs and the module docstrings of evgen/ and fastsim/, and
    paper/ is not in it.  The letter is the one document in this repository
    that will leave it, so it is checked here instead.
    """
    import json
    data = ROOT / "tools/retired_numbers.json"
    if not data.exists():
        return []
    try:
        entries = json.loads(data.read_text(encoding="utf-8"))
    except ValueError as exc:
        return ["tools/retired_numbers.json does not parse: %s" % exc]
    bad = []
    for rel in ("main.tex", "cover_letter.md"):
        path = PAPER / rel
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        for i, line in enumerate(text.split("\n"), start=1):
            code, _ = _split_comment(line) if rel.endswith(".tex") else (line, "")
            for e in entries:
                pat = e.get("retired")
                if not pat:
                    continue
                try:
                    m = re.search(pat, code)
                except re.error:
                    continue
                if m:
                    bad.append("paper/%s:%d carries the retired form %r "
                               "(current: %s) -- %s"
                               % (rel, i, m.group(0), e.get("current", "?"),
                                  e.get("note", "")))
    return bad


# --- Table 1, its caption and the abstract: no number is new ----------------
#
# The rest of the text is checked for *attribution* (a "% src:" comment naming
# a report section).  Table 1 and the abstract are held to more than that,
# because they are read without the sentences around them: every number in
# them must be a number one of two documents already prints -- Report 1's
# template, which is the letter's source, or the expected-numbers table of
# docs/reproduction_manual.md SS 7.  The declaration below names, for each,
# the string that document prints it in.  The check then asserts three things
# at once: the string is still in that document verbatim; the letter's value
# agrees with one of the numbers inside the string, to the precision that
# number is printed at; and nothing in Table 1 or the abstract is undeclared.
#
# Five numbers are in neither document, and are declared against the driver
# that measured them instead, with the reason.  They are the four inclusive
# per-bin event counts (Report 1 quotes the programme totals, not the counts
# of the four super-bins) and the coherent row's A/dA, which is that row's own
# division rather than a number Report 1 prints.

MANUAL = "docs/reproduction_manual.md"
MANUAL_SECTION = "## 7 \u00b7 Numbers to check against"
MANUAL_SECTION_END = "\n## 8 \u00b7"

# The two strings the four inclusive rows and the coherent row are read out of.
_R1_SPOTS_AMP = "7.4, 4.4, 9.5 and 9.5"
_R1_SPOTS_E1 = "1.7, 1.4, 2.7 and 4.5"
_R1_SPOTS_E10 = "0.55, 0.45, 0.87 and 1.4"
_R1_SPOTS_SIG = "43, 31, 35 and 21\u03c3"
_R1_COH_BIN = ("x \u2208 [0.0013, 0.0025], Q\u00b2 \u2208 [1, 1.7] GeV\u00b2, "
               "holds 1.75\u00d710\u2076")
_R1_COH_ERR = ("\u03b4\u00c2 = 1.8\u00d710\u207b\u00b3 (one year) and "
               "0.6\u00d710\u207b\u00b3 (ten years)")
_R1_A2 = "0.036 at P zz = 0.6, i.e. 0.060 per unit P zz"
_R1_FLOORS = "5\u03c3 floors at 0.9% and 0.3%"
_R1_BEAM = "e(10 GeV) \u00d7 \u2076Li(99.5 GeV/u)"
_MAN_SPOTS = ("(0.0282, 1.135) / (0.0112, 1.135) / (0.0708, 3.127) / "
              "(0.1413, 14.30)")

_DRIVER_N = ("the driver's own count; Report 1 quotes the programme totals "
             "(5.2\u00d710\u2079 accepted, 1.2\u00d710\u2078 coherent, "
             "1.7\u00d710\u2077 tagged), not the four super-bin counts")
_DRIVER_SIG = ("this row's own A/dA (0.060/0.0018); Report 1 prints the two "
               "5-sigma floors instead (R-PAPER 2026-09-16, item 22)")

# (where, role, literal, source, string or note[, slack note]).  "source" is
# R1, manual or drivers; for the drivers the fifth field is the reason, not a
# string to find.  A sixth field is a declared disagreement of one unit in the
# last digit the source prints, with the reason; there is one.
SOURCED = [
    # --- Table 1, the four inclusive super-bins -----------------------------
    ("Table 1", "bin", "0.0282", "manual", _MAN_SPOTS),
    ("Table 1", "bin", "0.0112", "manual", _MAN_SPOTS),
    ("Table 1", "bin", "0.0708", "manual", _MAN_SPOTS),
    ("Table 1", "bin", "0.141", "manual", _MAN_SPOTS),
    ("Table 1", "bin", "1.14", "manual", _MAN_SPOTS),
    ("Table 1", "bin", "3.13", "manual", _MAN_SPOTS),
    ("Table 1", "bin", "14.3", "manual", _MAN_SPOTS),
    ("Table 1", "n", "1.90", "drivers", _DRIVER_N),
    ("Table 1", "n", "2.81", "drivers", _DRIVER_N),
    ("Table 1", "n", "7.52", "drivers", _DRIVER_N),
    ("Table 1", "n", "2.85", "drivers", _DRIVER_N),
    ("Table 1", "amp", "7.42", "R1", _R1_SPOTS_AMP),
    # Report 1 prints this one as 4.4 where the driver's 4.3463e-3 rounds to
    # 4.3; the two agree to a unit in Report 1's last digit and the letter
    # prints the driver's own value.  Flagged to the authors on 2026-09-16.
    ("Table 1", "amp", "4.35", "R1", _R1_SPOTS_AMP,
     "Report 1 SS 5.1 prints 4.4 for this spot; the driver measures "
     "4.3463e-3, which is 4.3 at Report 1's two figures"),
    ("Table 1", "amp", "9.49", "R1", _R1_SPOTS_AMP),
    ("Table 1", "amp", "9.52", "R1", _R1_SPOTS_AMP),
    ("Table 1", "err1", "0.173", "R1", _R1_SPOTS_E1),
    ("Table 1", "err1", "0.142", "R1", _R1_SPOTS_E1),
    ("Table 1", "err1", "0.275", "R1", _R1_SPOTS_E1),
    ("Table 1", "err1", "0.446", "R1", _R1_SPOTS_E1),
    ("Table 1", "err10", "0.0547", "R1", _R1_SPOTS_E10),
    ("Table 1", "err10", "0.0450", "R1", _R1_SPOTS_E10),
    ("Table 1", "err10", "0.0869", "R1", _R1_SPOTS_E10),
    ("Table 1", "err10", "0.141", "R1", _R1_SPOTS_E10),
    ("Table 1", "sig", "43", "R1", _R1_SPOTS_SIG),
    ("Table 1", "sig", "31", "R1", _R1_SPOTS_SIG),
    ("Table 1", "sig", "35", "R1", _R1_SPOTS_SIG),
    ("Table 1", "sig", "21", "R1", _R1_SPOTS_SIG),
    # --- Table 1, the coherent row ------------------------------------------
    ("Table 1", "bin", "1.26", "R1", _R1_COH_BIN),
    ("Table 1", "bin", "2.51", "R1", _R1_COH_BIN),
    ("Table 1", "bin", "1.00", "R1", _R1_COH_BIN),
    ("Table 1", "bin", "1.66", "R1", _R1_COH_BIN),
    ("Table 1", "n", "1.75", "R1", _R1_COH_BIN),
    ("Table 1", "amp", "60.0", "R1", _R1_A2),
    ("Table 1", "err1", "1.80", "R1", _R1_COH_ERR),
    ("Table 1", "err10", "0.570", "R1", _R1_COH_ERR),
    ("Table 1", "sig", "33", "drivers", _DRIVER_SIG),
    # --- Table 1's caption ---------------------------------------------------
    ("Table 1 caption", "text", "10", "R1", _R1_BEAM),
    ("Table 1 caption", "text", "99.5", "R1", _R1_BEAM),
    ("Table 1 caption", "text", "0.60", "R1", "P zz = 0.60"),
    ("Table 1 caption", "text", "100", "R1", "100 fb\u207b\u00b9/u"),
    ("Table 1 caption", "text", "0.012", "R1",
     "\u222bx \u0394 dx = \u22120.012 \u03b1 s"),
    ("Table 1 caption", "text", "4.47", "R1",
     "\u27e8Q\u00b2\u27e9 = 4.47 GeV\u00b2"),
    ("Table 1 caption", "text", "13.5", "R1", "\u03b5 tag = 13.5%"),
    ("Table 1 caption", "text", "0.04", "R1", "f\u2080 = 0.04"),
    ("Table 1 caption", "text", "50", "R1", "50 GeV\u207b\u00b2"),
    ("Table 1 caption", "text", "0.20", "R1", "0.20 GeV"),
    ("Table 1 caption", "text", "0.060", "R1", _R1_A2),
    ("Table 1 caption", "text", "0.036", "R1", _R1_A2),
    ("Table 1 caption", "text", "0.018", "R1", "[0.018\\mathrm{-}0.059]"),
    ("Table 1 caption", "text", "0.059", "R1", "[0.018\\mathrm{-}0.059]"),
    ("Table 1 caption", "text", "9.01", "R1", _R1_FLOORS),
    ("Table 1 caption", "text", "2.85", "R1", _R1_FLOORS),
    # --- the abstract --------------------------------------------------------
    ("abstract", "text", "10", "R1", "10 fb\u207b\u00b9 per nucleon"),
    ("abstract", "text", "21", "R1", "21\u201343\u03c3"),
    ("abstract", "text", "43", "R1", "21\u201343\u03c3"),
    ("abstract", "text", "2", "R1", "2\u20139%"),
    ("abstract", "text", "9", "R1", "2\u20139%"),
]

_SOURCE_FILE = {"R1": REPORT1, "manual": MANUAL}

# The cells of one Table 1 row, and the raw value behind each.
_ROW_CELLS = (("bin", None), ("n", "n_1yr"), ("amp", "amp"),
              ("err1", "err_1yr"), ("err10", "err_10yr"),
              ("sig", "significance_1yr"))

_TEX_NUMBER = re.compile(r"(?<![\d.])\d+(?:\.\d+)?")
_POWER = re.compile(r"(?:\\times\s*)?10\s*\^\s*\{?-?\d+\}?")
_PERCENT = re.compile(r"(\d+(?:\.\d+)?)\s*(?:--\s*(\d+(?:\.\d+)?)\s*)?\\%")


def _tex_quantities(fragment):
    """The quantities one piece of the letter quotes, as printed literals.

    A quantity is a decimal, an integer of two digits or more, or a number
    carrying a per-cent sign; a bare single digit is notation (spin-1, IP6,
    3x3 cells, 5 sigma, the Q^2 = 1 edge) and carries nothing to source.
    Powers of ten, superscripts, subscripts and control sequences are removed
    first, so 1.90e8 is the quantity 1.90 and ^{6}Li is not a quantity.
    """
    s = _strip_tex_comments(fragment)
    keep = set()
    for m in _PERCENT.finditer(s.replace("$", " ")):   # 13.5\%, $2$--$9\%$
        keep.add(m.group(1))
        if m.group(2):
            keep.add(m.group(2))
    s = re.sub(r"\\(?:cite|ref|label|input|includegraphics|newcommand)\s*"
               r"(?:\[[^\]]*\])?\{[^}]*\}", " ", s)
    s = _POWER.sub(" ", s)
    s = re.sub(r"[\^_]\s*\{[^{}]*\}", " ", s)
    s = re.sub(r"[\^_]\s*\\?\w", " ", s)
    s = re.sub(r"\\[a-zA-Z]+", " ", s)
    s = re.sub(r"[${}~\\]", " ", s)
    for m in _TEX_NUMBER.finditer(s):
        tok = m.group(0)
        if "." in tok or len(tok.lstrip("0")) >= 2:
            keep.add(tok)
    return keep


def _letter_quantities():
    """[(where, role, literal, value)] for Table 1, its caption and the
    abstract.  `value` is the raw number behind a table cell, or None."""
    out = []
    seen = set()

    def add(where, role, literals, value=None):
        for lit in sorted(literals):
            if (where, role, lit) in seen:
                continue
            seen.add((where, role, lit))
            out.append((where, role, lit, value))

    if (PAPER / "figs/table1.json").exists():
        for row in _load_json("figs/table1.json").get("rows", []):
            vals = row.get("values", {})
            for role, key in _ROW_CELLS:
                cell = row.get({"sig": "significance"}.get(role, role), "")
                add("Table 1", role, _tex_quantities(cell),
                    None if key is None else vals.get(key))
    tex_path = PAPER / "table1.tex"
    if tex_path.exists():
        m = re.search(r"\\caption\{(.*?)\}\s*\n\s*\\label",
                      tex_path.read_text(encoding="utf-8"), re.S)
        if m:
            add("Table 1 caption", "text", _tex_quantities(m.group(1)))
    main = PAPER / "main.tex"
    if main.exists():
        m = re.search(r"\\begin\{abstract\}(.*?)\\end\{abstract\}",
                      main.read_text(encoding="utf-8"), re.S)
        if m:
            add("abstract", "text", _tex_quantities(m.group(1)))
    return out


def _significant(text):
    """The significant digits of a printed decimal: 0.60 -> '60', 1.90 ->
    '190', 0.0013 -> '13'.  Trailing zeros after a point are significant."""
    s = text.strip().lstrip("+-\u2212")
    s = s.replace(".", "") if "." in s else s
    s = s.lstrip("0")
    return s or "0"


def _rounded(value, k):
    """`value` as k significant digits, as a digit string."""
    if k < 1:
        return ""
    return ("%.*e" % (k - 1, abs(float(value)))).split("e")[0].replace(".", "")


def _agrees(literal, value, printed, slack=0):
    """Does the letter's number agree with a number the source prints?

    The comparison is on significant digits and ignores the power of ten:
    Report 1 factors it out of a list ("1.7, 1.4, 2.7 and 4.5 x10^-4") and the
    letter factors it into a column heading ("[10^-3]"), so the scales are not
    comparable as printed while the digits are.  Where the letter's raw value
    is known it is rounded to the source's precision, which is the honest
    comparison: the source's 2.7 is 2.7496e-4 rounded, and so is the letter's
    0.275, but rounding 0.275 again would give 2.8.
    """
    kp = len(_significant(printed))
    if value is None:
        k = min(kp, len(_significant(literal)))
        mine = _rounded(float(literal), k)
    else:
        k = kp
        mine = _rounded(value, k)
    if not k:
        return False
    theirs = _rounded(float(printed), k)
    if mine == theirs:
        return True
    # a declared slack is one unit in the last digit the source printed
    return slack and len(mine) == len(theirs) \
        and abs(int(mine) - int(theirs)) <= slack


def _flatten_html(text):
    import html as _html
    text = re.sub(r"<script.*?</script>", " ", text, flags=re.S)
    tex = " ".join(re.findall(r'data-tex="([^"]*)"', text))
    body = re.sub(r"<[^>]+>", " ", text)
    return re.sub(r"\s+", " ", _html.unescape(body) + " "
                  + _html.unescape(tex))


def _source_text(which):
    """The flattened text of one source document, or None."""
    path = ROOT / _SOURCE_FILE[which]
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    if which == "R1":
        return _flatten_html(text)
    if MANUAL_SECTION not in text:
        return None
    body = text[text.index(MANUAL_SECTION):]
    if MANUAL_SECTION_END in body:
        body = body[:body.index(MANUAL_SECTION_END)]
    return re.sub(r"\s+", " ", body)


def _number_source_issues():
    """Every number of Table 1, its caption and the abstract is declared, and
    every declaration still holds."""
    quantities = _letter_quantities()
    if not quantities:
        return ["paper/figs/table1.json and paper/main.tex quote no numbers: "
                "run `bash paper/build.sh --figures`"]
    declared = {}
    bad = []
    for row in SOURCED:
        where, role, lit, source, printed = row[:5]
        slack_note = row[5] if len(row) > 5 else None
        if (where, role, lit) in declared:
            bad.append("SOURCED declares %s / %s / %s twice"
                       % (where, role, lit))
        declared[(where, role, lit)] = (source, printed, slack_note)
    corpus = {}
    used = set()
    for where, role, lit, value in quantities:
        entry = declared.get((where, role, lit))
        if entry is None:
            bad.append("the letter's %s quotes %s (%s), which is declared in "
                       "no source: add it to SOURCED in "
                       "tools/checks/paper_numbers.py against the string "
                       "Report 1 or the manual prints it in"
                       % (where, lit, role))
            continue
        used.add((where, role, lit))
        source, printed, slack_note = entry
        if source == "drivers":
            if not printed:
                bad.append("%s / %s is declared against the drivers with no "
                           "reason" % (where, lit))
            continue
        if source not in corpus:
            corpus[source] = _source_text(source)
        text = corpus[source]
        if text is None:
            bad.append("cannot read %s, the source declared for the %s of %s"
                       % (_SOURCE_FILE[source], lit, where))
            continue
        if printed not in text:
            bad.append("%s no longer carries %r, which the %s of the letter's "
                       "%s is read out of" % (_SOURCE_FILE[source], printed,
                                              lit, where))
            continue
        numbers = _TEX_NUMBER.findall(printed)
        slack = 1 if slack_note else 0
        if not any(_agrees(lit, value, n, slack) for n in numbers):
            bad.append("the letter's %s quotes %s in %s, which does not agree "
                       "with any number in %r (%s)"
                       % (where, lit, role, printed, _SOURCE_FILE[source]))
        elif slack and any(_agrees(lit, value, n) for n in numbers):
            bad.append("%s / %s / %s carries a declared slack it no longer "
                       "needs: it now agrees exactly, so drop the sixth field"
                       % (where, role, lit))
    for key in declared:
        if key not in used:
            bad.append("SOURCED declares %s / %s / %s, which the letter no "
                       "longer quotes: drop the row" % key)
    return bad


def _letter_text_issues():
    return (_text_issues() + _abstract_issues()
            + _cover_letter_issues() + _retired_in_paper_issues())

def _letter_figure_issues():
    return _table_issues() + _provenance_of_built_figures()


if not _STANDALONE:

    @check("paper: the letter scaffold has the files plans/07 WP6 names")   # noqa: F821
    def _():
        return _scaffold_issues()

    @check("paper: refs.bib and main.tex's citations are an exact "          # noqa: F821
           "correspondence -- every cite resolves, every entry is cited, no "
           "key is duplicated or in both bibliography files")
    def _():
        if not (PAPER / "refs.bib").exists():
            return ["paper/refs.bib is missing"]
        return _bib_issues()[0]

    @check("paper: every refs.bib entry is an INSPIRE record or is flagged "  # noqa: F821
           "hand-written and accounted for in refs_provenance.md")
    def _():
        if not (PAPER / "refs.bib").exists():
            return ["paper/refs.bib is missing"]
        return _provenance_issues()

    @check("paper: every numbered reference of Report 1 and of the coherent "  # noqa: F821
           "note is represented in paper/refs.bib or paper/refs_reserve.bib")
    def _():
        return _coverage_issues()

    @check("paper: figs/README.md registers four letter figures against "     # noqa: F821
           "producing scripts that exist")
    def _():
        return _figure_issues()

    @check("paper: the four letter figures and Table 1 are built, and every "  # noqa: F821
           "number in Table 1 is a value figs/fig2.json or fig4.json measured")
    def _():
        return _letter_figure_issues()

    @check("paper: every number in Table 1, in its caption and in the "        # noqa: F821
           "abstract is a number Report 1's template or the manual's "
           "expected-numbers table prints, in the string it prints it in")
    def _():
        return _number_source_issues()

    @check("paper: main.tex carries the programme's author line, affiliation " # noqa: F821
           "and writing-assistance line")
    def _():
        return _frontmatter_issues()

    @check("paper: every number in the letter's text names the report "       # noqa: F821
           "section it comes from, the abstract is inside its budget, the "
           "cover letter states the two verified firsts, and no retired form "
           "reaches either")
    def _():
        return _letter_text_issues()


def main():
    entries = _bib_entries()
    hand = [k for _, k, b in entries if "HAND-WRITTEN" in b]
    bib_bad, n_cited, n_unres = _bib_issues()
    groups = [
        ("scaffold files", _scaffold_issues()),
        ("citations", bib_bad),
        ("entry provenance", _provenance_issues()),
        ("source coverage", _coverage_issues()),
        ("figure register", _figure_issues()),
        ("letter figures", _letter_figure_issues()),
        ("declared numbers", _number_source_issues()),
        ("front matter", _frontmatter_issues()),
        ("letter text", _letter_text_issues()),
    ]
    reserve = _bib_entries(RESERVE)
    hand_r = [k for _, k, b in reserve if "HAND-WRITTEN" in b]
    print("paper/refs.bib: %d entries (%d from INSPIRE, %d hand-written); "
          "%s: %d more (%d, %d)"
          % (len(entries), len(entries) - len(hand), len(hand), RESERVE,
             len(reserve), len(reserve) - len(hand_r), len(hand_r)))
    labels, _ = _covered_labels()
    n1, n2 = _source_list_sizes()
    n_src_unres = (len([i for i in range(1, n1 + 1) if ("R1", i) not in labels])
                   + len([i for i in range(1, n2 + 1) if ("N", i) not in labels]))
    print("source lists: Report 1 [1]-[%d], coherent note [1]-[%d]" % (n1, n2))
    print("main.tex: %d distinct citation key(s), %d number(s) declared in "
          "Table 1, its caption and the abstract"
          % (n_cited, len(_letter_quantities())))
    print("%d unresolved" % (n_unres + n_src_unres))
    print()
    nbad = 0
    for name, bad in groups:
        nbad += len(bad)
        print("  %-18s %s" % (name, "ok" if not bad else "FAIL (%d)" % len(bad)))
        for b in bad:
            print("      - %s" % b)
    print()
    print("%d problem(s)" % nbad)
    return 1 if nbad else 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
